---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: vault
  labels:
    run: vault
spec:
  serviceAccountName: vault
  containers:
    - name: vault
      image: vault
      args: [ "server", "-dev", "-dev-listen-address=0.0.0.0:8200", "-dev-root-token-id=$(VAULT_TOKEN)" ]
      env:
        - name: VAULT_ADDR
          value: http://localhost:8200
        - name: VAULT_TOKEN
          value: root-token
      ports:
        - containerPort: 8200
          name: vault
      lifecycle:
        postStart:
          exec:
            command:
              - /bin/sh
              - -c
              - |
                {
                set -ex
                until vault status; do
                  sleep 3
                done
                vault token lookup
                vault auth enable kubernetes
                vault write auth/kubernetes/config \
                  kubernetes_host=https://kubernetes \
                  kubernetes_ca_cert=@/run/secrets/kubernetes.io/serviceaccount/ca.crt \
                  token_reviewer_jwt=@/run/secrets/kubernetes.io/serviceaccount/token
                vault read auth/kubernetes/config
                echo '{"path": {"secret/data/app/*": {"capabilities": ["read"]}}}' | vault policy write app -
                vault write auth/kubernetes/role/app \
                  bound_service_account_names=app \
                  bound_service_account_namespaces=default \
                  policies=app \
                  ttl=4h
                vault read auth/kubernetes/role/app
                # better would be to use a dynamic database secret, but simple kv is enough for a demo
                vault kv put secret/app/db username=app password=abc123 updated="$(date)"
                } 2>&1 | tee /var/postStart.log
---
apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  ports:
    - port: 80
      targetPort: vault
  selector:
    run: vault
  type: NodePort
