---
apiVersion: v1
kind: Service
metadata:
  name: mutating-admission-webhook
  namespace: mutating-admission-webhook
  labels:
    run: mutating-admission-webhook
spec:
  ports:
  - name: webhook
    port: 443
  selector:
    run: mutating-admission-webhook
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mutating-admission-webhook
  namespace: mutating-admission-webhook
  labels:
    run: mutating-admission-webhook
spec:
  replicas: 1
  template:
    metadata:
      name: mutating-admission-webhook
      labels:
        run: mutating-admission-webhook
    spec:
      containers:
        - name: webhook
          image: mutating-admission-webhook
          imagePullPolicy: Never
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
          ports:
            - containerPort: 443
              name: webhook
      volumes:
        - name: webhook-certs
          secret:
            secretName: mutating-admission-webhook
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-admission-webhook
webhooks:
  - name: mutating-admission-webhook.example.com
    clientConfig:
      service:
        name: mutating-admission-webhook
        namespace: mutating-admission-webhook
        path: "/mutating-pods"
      caBundle: "CA_BUNDLE_HERE"
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        mutating-admission-webhook: enabled
