apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    run: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: nginx
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  type: NodePort
  ports:
    - name: nginx
      port: 80
      protocol: TCP
      targetPort: nginx
  selector:
    run: nginx
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  labels:
    run: nginx
  annotations:
    # See https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  # See https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/spec/
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: nginx
              servicePort: 80
